mod utils;
mod test_01_element_properties;
mod test_02_static_trusses;
mod test_03_static_beams;
mod test_04_static_string;
mod test_05_linear_oscillator;
mod test_06_nonlinear_oscillator;
mod test_07_example_bows;
mod test_08_string_damping;