mod utils;
mod test_00_command_line_interface;
mod test_01_element_properties;
mod test_02_static_trusses;
mod test_03_static_beams;
mod test_04_linear_oscillator;
mod test_05_nonlinear_oscillator;
mod test_06_example_bows;
mod test_07_string_damping;