[book]
authors = ["Stefan Pfeifer"]
language = "en"
title = "VirtualBow User Manual"

[build]
build-dir = "../../gui/resources/docs/user-manual"

[output.html]
additional-css = ["theme/justify.css", "theme/images.css", "theme/katex.min.css"]

[preprocessor.katex]
no-css = true    # KaTeX stylesheet and fonts are served from the book itself
