name: Coverage

on:
  pull_request:

jobs:
  code-coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage for solver tests
        run: |
          cd rust/virtualbow
          rustup default nightly
          cargo llvm-cov --release --branch  --no-report
          cargo llvm-cov report --release --html --output-dir "."
          cargo llvm-cov report --release --text --output-dir "."

      - name: Upload coverage report artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: rust/virtualbow/html

      - name: Create report summary file
        run: |
          echo "# Coverage Report for [${GITHUB_SHA::7}](https://github.com/bow-simulation/virtualbow/commit/${GITHUB_SHA})" >> summary.md
          echo "See the summary below or [download the full report](${{ steps.artifact-upload-step.outputs.artifact-url }})." >> summary.md
          echo '```' >> summary.md
          echo "$(<rust/virtualbow/text/index.txt)" >> summary.md
          echo '```' >> summary.md

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary-file
          path: summary.md

      - name: Add summary file as a pull request comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: summary.md
